//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Competition
{
    using System;
    using System.Collections.Generic;
    
    public partial class competition
    {
        public int CompetitionID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public string CompetitionName { get; set; }
        public string Details { get; set; }
        public int Groups { get; set; }
        public int TeamLimit { get; set; }
        public string Awards { get; set; }
        public System.DateTime DeleteTime { get; set; }
    }
}
