//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Competition
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        /// <summary>
        /// 用户名
        /// </summary>
        public string StudentID { get; set; }
        public int ClassID { get; set; }
        public int Grade { get; set; }
        public int Gender { get; set; }
        /// <summary>
        /// 学号
        /// </summary>
        public string StudentName { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Phonenumber { get; set; }
        public int ID { get; set; }
        public Nullable<sbyte> HasPermission { get; set; }
    }
}
