//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Competition
{
    using System;
    using System.Collections.Generic;
    
    public partial class team
    {
        public int ID { get; set; }
        public int CID { get; set; }
        public int Group { get; set; }
        public int Number { get; set; }
        public string Member { get; set; }
        public int Award { get; set; }
    }
}
